<style>

    /* ~~~~~~~~~~ kalender ~~~~~~~~~~ */
    .yui-skin-sam{width: 195px;}
    .yui-skin-sam .yui-calcontainer {
        border: none !important;
    }
    .yui-skin-sam .yui-calcontainer {
        background-color: #F2F2F2;
        border: 1px solid #808080;
        padding: 10px;
    }
    .calweekdaycell {
        background-color:#1B2D79 !important;
        color:white !important;
    }
    .calheader {
        color:#1B2D79 !important;
    }

    .calcellhover a {
        background-color:white !important;
        color:#9BA8B0 !important;
    }

    .selector {
        color:#9BA8B0 !important;
    }

    .today {
        background-color:#1B2D79 !important;
    }

    .today a {
        font-weight:bold !important;
        color:#1B2D79 !important;
    }

    .highlight1 {
        background-color:#1B2D79 !important;
    }

    .highlight1 a {
        color:#1B2D79 !important;
        background-color:#D9DFE4 !important;
    }

    .oom {
        background-color:#F4FAFF !important;
        color:#D5E2ED !important;
    }

    .item_highlight {
        background-color: #D9DFE4 !important;
        padding:10px;
        margin-left:-10px;
        margin-right:-10px;
    }

    #veranstaltungen {
        background-color:#1B2D79;
        color:white;
        width:185px;
        padding:5px;
        font-weight:bold;
    }
    #termin {
        background-color:#1B2D79;
        color:white;
        width: 185px;
        padding:5px;
        font-size:10px;
    }

    #veranstaltungsteaser .veranstaltung h4{font-size: 14px;margin: 3px 0;}

    #veranstaltungsteaser .veranstaltung{
        border:1px solid #a2b2bf;
        border-top: none;
        padding:6px 16px;
        width: 161px;
    }
    #veranstaltungsteaser .lightblue{color:#627D90;}

    #veranstaltungen{position: relative;}

    #veranstaltungen #infobox{
        position: absolute;
        top: -1px;
        left: -205px;
        min-height: 230px;
        width: 200px;
        background-color: #F7F7F7;
        border: 2px solid #a2b2bf;
        border-radius: 10px;
        color: #666;
        padding-top: 5px;
        display: none;

    }

    #veranstaltungen #infobox #date{
        padding-left: 10px;
        margin: 20px 0 5px 0;
    }

    #veranstaltungen #infobox #close{
        cursor: pointer;
        padding-left: 5px;
    }

    #veranstaltungen #infobox .calelement{
        border-top: 1px solid #a2b2bf;
        padding:  15px 0;
    }
    #veranstaltungen #infobox .calelement h2{
        margin: 0!important;
        font-size: 12px;
        padding-bottom: 5px;
        line-height: 30px;
        color: #6681A3!important;
    }

    #veranstaltungen #infobox .calelement h1{
        font-size: 14px;
        margin: 0!important;
        line-height: 14px;
    }

    #veranstaltungen #infobox .calelement h1, #veranstaltungen #infobox .calelement h2{padding: 0 10px;}

    #hiddenCalElement{display: none;}


    .close {
        color: #000000;
        float: right;
        font-size: 20px;
        font-weight: bold;
        line-height: 20px;
        text-shadow: 0 1px 0 #FFFFFF;
        font-family: Verdana,Helvetica,Arial,sans-serif;
        padding-right: 10px;
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=20)";
        filter: alpha(opacity=20);
        -moz-opacity: 0.2;
        -khtml-opacity: 0.2;
        opacity: 0.2;
    }
    .close:hover{
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
        filter: alpha(opacity=100);
        -moz-opacity: 1;
        -khtml-opacity: 1;
        opacity: 1;
    }



</style>

<?php if ($this->calendar) : #CALENDAR IF?>

    <script type="text/javascript" src="<?php echo $this->jqueryMin; ?>"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->fontsMinCSS; ?>" />
    <script type="text/javascript" src="<?php echo $this->yahoodom; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->calendarJS; ?>"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->calendarCSS; ?>" />

    <div id="hiddenCalElement">
        <div id="item_new" class="calelement">
            <h2>DATUM</h2>
            <h1>HEADLINE</h1>
        </div>
    </div>


    <div  class="yui-skin-sam">
        <div id="veranstaltungen">
            <center><?php if ($this->lang == "de"): ?>Veranstaltungen<?php else: ?>Events<?php endif; ?></center>
            <div id="infobox">
                <span id="close" class="close" onclick="$('#infobox').hide();">x</span>
                <div style="margin-top:10px;">
                    <p id="date"></p>


                </div>
            </div>
        </div>
        <div id="cal1Container"></div>
    </div>
    <script type="text/javascript">
                    YAHOO.namespace("example.calendar");

                    function getPreparedArray()
                    {
                        var eventArray = new Array();
    <?php
    $i = 0;
    foreach ($this->calelements as $entry) {

        if (strstr($entry["url"], '[[intern:')) {
            $dummy = str_replace('[[intern:', '', $entry["url"]);
            $pid = str_replace(']]', '', $dummy);
            $pid = intval(trim($pid));
            $url = $this->baseUrlWithoutIndex . $pid;
            $urlType = "extern";
        }
        elseif (empty($entry["url"])) {
            $url = $this->baseUrl;
            $urlType = "intern";
        }
        else {
            $url = $entry["url"];
            $urlType = "extern";
        }

        echo "" . PHP_EOL;
        echo "eventArray[" . $i . "] = new Object();" . PHP_EOL;
        echo "eventArray[" . $i . "]['id'] = " . $entry["id"] . ";" . PHP_EOL;
        echo "eventArray[" . $i . "]['startdate'] = " . substr($entry["free_date"], 0, 8) . ";" . PHP_EOL;
        echo "eventArray[" . $i . "]['enddate'] = " . substr($entry["opt7text"], 0, 8) . ";" . PHP_EOL;
        echo "eventArray[" . $i . "]['headline'] ='" . $entry["description"] . "';" . PHP_EOL;
        echo "eventArray[" . $i . "]['url'] ='" . $url . "';" . PHP_EOL;
        echo "eventArray[" . $i . "]['urlType'] ='" . $urlType . "';" . PHP_EOL;
        echo "" . PHP_EOL;
        $i++;
    }
    ?>
                        return eventArray;
                    }

                    function dateToLocaleString(dt, cal) {
                        var wStr = cal.cfg.getProperty("WEEKDAYS_LONG")[dt.getDay()];
                        var dStr = dt.getDate();
                        var mStr = cal.cfg.getProperty("MONTHS_LONG")[dt.getMonth()];
                        var yStr = dt.getFullYear();
                        return (wStr + ", " + dStr + " " + mStr + " " + yStr);
                    }

                    function mySelectHandler(type, args, obj) {
                        var selected = args[0];
                        var selDate = this.toDate(selected[0]);
                        var myDate = new Date(selDate);

                        var y = String(myDate.getFullYear());
                        var monat = myDate.getMonth() + 1;
                        if (monat < 10) {
                            var m = "0" + String(monat);
                        } else {
                            var m = String(monat);
                        }

                        if (myDate.getDate() < 10) {
                            var d = "0" + String(myDate.getDate());
                        } else {
                            var d = String(myDate.getDate());
                        }

                        var selectedIntDate = y + m + d;

                        var parray = getPreparedArray();
                        var bool = false;
                        $('#infobox div.calelement').remove();

                        for (var i = parray.length - 1; i >= 0; i--) {
                            if (selectedIntDate >= parray[i]['startdate'] & selectedIntDate <= parray[i]['enddate']) {
                                var bool = true;

                                var year1 = String(parray[i]['startdate']).substr(0, 4);
                                var month1 = String(parray[i]['startdate']).substr(4, 2);
                                var day1 = String(parray[i]['startdate']).substr(6, 2);

                                var year2 = String(parray[i]['enddate']).substr(0, 4);
                                var month2 = String(parray[i]['enddate']).substr(4, 2);
                                var day2 = String(parray[i]['enddate']).substr(6, 2);

                                var url = parray[i]['url'];
                                var urltype = parray[i]['urlType'];

                                $('#hiddenCalElement #item_new').clone()
                                        .attr('id', 'item_' + i)
                                        .insertAfter('#infobox p#date');

                                $('#item_' + i).css('display', 'block');
                                $('#item_' + i + '.calelement h2').text(day1 + '.' + month1 + '.' + year1 + ' - ' + day2 + '.' + month2 + '.' + year2);
                                $('#item_' + i + '.calelement h1').html(parray[i]['headline'] + '<span style="font-size:11px;">...[<a href="#" >&nbsp;</a>]<span>');
    <?php if ($this->lang == "de"): ?>
                                    $('#item_' + i + '.calelement h1 span a').text('mehr');
    <?php else: ?>
                                    $('#item_' + i + '.calelement h1 span a').text('more');
    <?php endif; ?>
                                if (urltype !== 'intern') {
                                    $('#item_' + i + '.calelement h1 span a').attr('target', '_blank');
                                }
                                $('#item_' + i + '.calelement h1 span a').attr('href', url);
                                $('#item_' + i + '.calelement h1 span a').addClass(urltype);
                            }
                        }
                        if (bool) {
                            $('#infobox').show();
                            $('#infobox #date').html(dateToLocaleString(selDate, this));
                        } else {
                            $('#infobox').hide();
                        }
                    }

                    YAHOO.example.calendar.init = function() {
                        YAHOO.example.calendar.cal1 = new YAHOO.widget.Calendar("cal1", "cal1Container");
                        YAHOO.example.calendar.cal1.selectEvent.subscribe(mySelectHandler, YAHOO.example.calendar.cal1, true);

                        YAHOO.example.calendar.cal1.cfg.setProperty("DATE_FIELD_DELIMITER", ".");

                        YAHOO.example.calendar.cal1.cfg.setProperty("MDY_DAY_POSITION", 1);
                        YAHOO.example.calendar.cal1.cfg.setProperty("MDY_MONTH_POSITION", 2);
                        YAHOO.example.calendar.cal1.cfg.setProperty("MDY_YEAR_POSITION", 3);

                        YAHOO.example.calendar.cal1.cfg.setProperty("MD_DAY_POSITION", 1);
                        YAHOO.example.calendar.cal1.cfg.setProperty("MD_MONTH_POSITION", 2);

    <?php if ($this->lang == "de"): ?>
                            YAHOO.example.calendar.cal1.cfg.setProperty("MONTHS_SHORT", ["Jan", "Feb", "M\u00E4r", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("MONTHS_LONG", ["Januar", "Februar", "M\u00E4rz", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("WEEKDAYS_1CHAR", ["S", "M", "D", "M", "D", "F", "S"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("WEEKDAYS_SHORT", ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("WEEKDAYS_MEDIUM", ["Son", "Mon", "Die", "Mit", "Don", "Fre", "Sam"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("WEEKDAYS_LONG", ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"]);
    <?php else: ?>
                            YAHOO.example.calendar.cal1.cfg.setProperty("MONTHS_SHORT", ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("MONTHS_LONG", ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("WEEKDAYS_1CHAR", ["S", "M", "D", "M", "D", "F", "S"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("WEEKDAYS_SHORT", ["Su", "Mo", "Tu", "Wd", "Th", "Fr", "Sa"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("WEEKDAYS_MEDIUM", ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]);
                            YAHOO.example.calendar.cal1.cfg.setProperty("WEEKDAYS_LONG", ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]);
    <?php endif; ?>
    <?php foreach ($this->calelements as $entry) : ?>
                            YAHOO.example.calendar.cal1.addRenderer("<?php
        $year = substr($entry['free_date'], 0, 4);
        $month = substr($entry['free_date'], 4, 2);
        $day = substr($entry['free_date'], 6, 2);

        $date2 = "";
        if (!empty($entry["opt7text"])) {
            $year2 = substr($entry['opt7text'], 0, 4);
            $month2 = substr($entry['opt7text'], 4, 2);
            $day2 = substr($entry['opt7text'], 6, 2);

            $date2 = ' - ' . $day2 . '.' . $month2 . '.' . $year2;
        }
        else {
            $date2 = "-" . $day . '.' . $month . '.' . $year;
        }
        echo $day . '.' . $month . '.' . $year . $date2;
        ?>", YAHOO.example.calendar.cal1.renderCellStyleHighlight1);
    <?php endforeach; ?>
                        YAHOO.example.calendar.cal1.render();
                    };

                    YAHOO.util.Event.onDOMReady(YAHOO.example.calendar.init);
    </script>

    <div style="clear:both" ></div>

<?php endif; #CALENDAR ENDIF?>

<?php if (!empty($this->data)) : ?>

    <div id="termin">
        <center><?php if ($this->lang == "de"): ?>n&auml;chste Veranstaltungen<?php else: ?>next event<?php endif; ?>: <?php
            $year = substr($this->data[0]['free_date'], 0, 4);
            $month = substr($this->data[0]['free_date'], 4, 2);
            $day = substr($this->data[0]['free_date'], 6, 2);

            echo $day . '.' . $month . '.' . $year;
            ?></center>
    </div>

    <div id="calendar_events_for_current_month">

        <div id="veranstaltungsteaser">
                    <?php foreach ($this->data as $entry) : ?>
                <div class="veranstaltung">
                    <div class="lightblue">
                        <?php
                        $year = substr($entry['free_date'], 0, 4);
                        $month = substr($entry['free_date'], 4, 2);
                        $day = substr($entry['free_date'], 6, 2);

                        $date2 = "";
                        if ($entry["opt7text"] != $entry["free_date"]) {
                            $year2 = substr($entry['opt7text'], 0, 4);
                            $month2 = substr($entry['opt7text'], 4, 2);
                            $day2 = substr($entry['opt7text'], 6, 2);

                            $date2 = ' - ' . $day2 . '.' . $month2 . '.' . $year2;
                        }
                        echo $day . '.' . $month . '.' . $year . $date2;
                        ?>
                    </div>
                    <div class="lightblue">
                            <?php echo $entry["opt4text"]; ?>
                    </div>
                    <h4><?php echo $entry["description"]; ?><span style="font-size: 11px;" >
                            <?php
                            if ($this->lang == "de") {
                                $morelabel = "mehr";
                            }
                            else {
                                $morelabel = "more";
                            }

                            if (strstr($entry["url"], '[[intern:')) {
                                $dummy = str_replace('[[intern:', '', $entry["url"]);
                                $pid = str_replace(']]', '', $dummy);
                                $pid = intval(trim($pid));

                                $url = $this->baseUrlWithoutIndex . $pid;
                                $moreHref = "...[<a class=\"intern\" target=\"_blank\" href=\"" . $url . "\">" . $morelabel . "</a>]";
                            }
                            elseif (empty($entry["url"])) {
                                $url = $this->baseUrl;
                                $moreHref = "...[<a class=\"intern\"  href=\"" . $url . "\">" . $morelabel . "</a>]";
                            }
                            else {
                                $url = $entry["url"];
                                $moreHref = "...[<a class=\"intern\" target=\"_blank\" href=\"" . $url . "\">" . $morelabel . "</a>]";
                            }
                            echo $moreHref;
                            ?></span></h4>
                </div>
    <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
